Feature/api 5 otp sms request
responsa/responsa-plugin-amga-reclami pull request #1
Opened 2021-04-09 15:44 UTC by SergioIacobellis

Implementazione API per invio sms e generazione codice OTP.

2021-04-09 15:58 UTC, andrerinaldi requested changes
Direi di spostare almeno la funzione che genera codici OTP casuali in un file di utility a parte, per il quale scrivere gli opportuni test in modo da verificare anche la reale randomicità dei codici OTP.

2021-04-12 07:06 UTC, davidefinellieuris requested changes
se i commenti non sono chiari, fammi un fischio

2021-04-12 07:06 UTC, davidefinellieuris commented on app/test/application/smsService.test.js
> +})
aggiungere test anche per i casi d'errore non solo l'happy ending e i test per le funzioni presenti nel sut

2021-04-12 07:06 UTC, davidefinellieuris commented on app/test/helper.js
> +  }
refactor per togliere questo if then else if

2021-04-12 07:06 UTC, davidefinellieuris commented on app/test/routes/actions/example/exampleRoute.test.js
> +    await helper.checkResponses('/actions/example', responses)
questo await non è necessario ... è un test async

2021-04-12 07:06 UTC, davidefinellieuris commented on app/test/routes/actions/smsService/smsServiceRoute.test.js
> +    await helper.checkResponses('/actions/smsService', responses)
come sopra

2021-04-12 07:06 UTC, davidefinellieuris commented on app/test/routes/actions/smsService/smsServiceRoute.test.js
> +})
con un numero di telefono tipo "123456748999" o "4564asdasda6546" cosa deve succedere?

2021-04-12 09:45 UTC, davidefinellieuris requested changes

2021-04-12 09:45 UTC, davidefinellieuris commented on app/src/application/otpGenerator.js
> +}
module.exports.generateOtp =() => Math.floor ......

2021-04-12 09:45 UTC, davidefinellieuris commented on app/src/application/smsMessageBuilder.js
> +}
come sopra

2021-04-12 09:47 UTC, davidefinellieuris commented on app/src/application/smsService.js
> +}
@SergioIacobellis quando risolvi qualcosa con un commit ... vieni a specificarlo qui

2021-04-12 09:52 UTC, SergioIacobellis commented on app/src/application/smsService.js
> +}
Inseriti test cases

2021-04-12 09:55 UTC, davidefinellieuris commented on app/src/application/otpGenerator.js
> +}
@SergioIacobellis come prima ... aggiorna le singole conversazioni per cui fai i commit ... queste due le chiudo io

2021-04-12 10:01 UTC, SergioIacobellis commented on app/src/models/smsService.js
> +  description: 'Il codice di verifica 200',
OK

2021-04-12 10:31 UTC, SergioIacobellis commented on app/src/models/smsService.js
> +}
Added

2021-04-12 10:45 UTC, SergioIacobellis commented on app/test/routes/actions/smsService/smsServiceRoute.test.js
> +})
la function ritorna null. aggiunto test case

2021-04-12 10:47 UTC, davidefinellieuris requested changes

2021-04-12 10:47 UTC, davidefinellieuris commented on app/test/application/smsService.test.js
> +})
@SergioIacobellis non devi chiudere tu la conversation ... devi solamente aggiungere un commento che descriva quello che hai fatto per risolvere la richiesta. 
Qui mi aspettavo un errore non un output vuoto ... altrimenti ritorniamo un 200 con null.

2021-04-12 10:51 UTC, SergioIacobellis commented on app/src/routes/actions/smsService/smsServiceRoute.js
> +}
Quali commenti?

2021-04-12 10:52 UTC, SergioIacobellis commented on app/test/helper.js
> +  }
che tipo di refactor vuoi fare qui?

2021-04-12 10:57 UTC, davidefinellieuris commented on app/test/helper.js
> +  }
actual = actual.get || actual.post

2021-04-12 10:58 UTC, davidefinellieuris commented on app/test/routes/actions/smsService/smsServiceRoute.test.js
> +})
come scritto sopra ... non deve essere null ma sollevare eccezione

2021-04-12 11:22 UTC, SergioIacobellis commented on app/test/helper.js
> +  }
eseguito refactor

2021-04-12 11:24 UTC, SergioIacobellis commented on app/test/application/smsService.test.js
> +})
inseriti altri test cases

2021-04-12 11:52 UTC, SergioIacobellis commented on app/test/routes/actions/smsService/smsServiceRoute.test.js
> +})
fatto

2021-04-12 12:09 UTC, davidefinellieuris commented on app/test/application/smsService.test.js
> +})
throw not return

2021-04-12 12:38 UTC, SergioIacobellis commented on app/test/application/smsService.test.js
> +})
inserita throw exc e adattato test case

2021-04-12 12:47 UTC, davidefinellieuris commented on app/src/models/smsService.js
> +module.exports.SmsService = {
come ci siamo detti stamattina, usciamo con un oggetto json vanilla

2021-04-12 14:30 UTC, SergioIacobellis commented on app/src/application/config.js
> +  }
fatto

2021-04-13 09:45 UTC, davidefinellieuris approved these changes
ok

2021-04-13 09:58 UTC, andrerinaldi approved these changes
ok

2021-04-13 09:58 UTC, merged