Feature/api 3 writing privacy acceptance
responsa/responsa-plugin-amga-reclami pull request #4
Opened 2021-04-14 13:44 UTC by SergioIacobellis

Come concordato su Teams, all'interno della folder crm ho inserito la folder privacy contenente la route dell'API privacy acceptance.

2021-04-14 14:49 UTC, andrerinaldi requested changes

2021-04-14 14:49 UTC, andrerinaldi commented on app/src/routes/actions/privacy/privacyAcceptanceRoute.js
> +    },
il 401 è gestito ad un livello superiore con un decorator di fastify, eliminerei la casistica dallo schema della response

2021-04-14 14:49 UTC, andrerinaldi commented on app/src/models/privacyAcceptance.js
> +}
il 401 è gestito ad un livello superiore con un decorator di fastify, eliminerei la casistica dallo schema della response

2021-04-14 14:49 UTC, andrerinaldi commented on app/src/routes/actions/privacy/privacyAcceptanceRoute.js
> +    })
rimuoviamo la roba inutile (la riga commentata), keep it simple

2021-04-14 14:49 UTC, andrerinaldi commented on app/src/routes/actions/privacy/privacyAcceptanceRoute.js
> +    const result = await zohoService.postData('/form/Privacy', postData)
i postData non starei a definirli in una costante, li butterei direttamente nella chiamata alla function.. sempre per la filosofia meno linee di codice ho, meglio sto

2021-04-14 14:49 UTC, andrerinaldi commented on app/test/routes/actions/privacy/responses.js
> +}
stesso discorso di sopra per il 401

2021-04-14 14:49 UTC, andrerinaldi commented on app/test/routes/actions/privacy/privacyAcceptanceRoute.test.js
> +  })
chiedo per ignoranza e perché non ho trovato riferimenti nel codice.. la validazione delle mail chi la fa? Zoho?

2021-04-14 14:49 UTC, andrerinaldi commented on app/test/routes/actions/privacy/privacyAcceptanceRoute.test.js
> +  it('Privacy Acceptance - Bad request with invalid parameter', async () => {
aggiungiamo anche il vincolo di 'required' per entrambi i parametri di input

2021-04-14 15:04 UTC, SergioIacobellis commented on app/src/routes/actions/privacy/privacyAcceptanceRoute.js
> +    },
done, ma perchè non farlo anche per l'internal server error 500?

2021-04-14 15:04 UTC, SergioIacobellis commented on app/src/models/privacyAcceptance.js
> +}
done

2021-04-14 15:04 UTC, SergioIacobellis commented on app/src/routes/actions/privacy/privacyAcceptanceRoute.js
> +    })
dimenticanza mia..done

2021-04-14 15:06 UTC, SergioIacobellis commented on app/src/routes/actions/privacy/privacyAcceptanceRoute.js
> +    const result = await zohoService.postData('/form/Privacy', postData)
done..sempre a patto di non andare a discapito della lettura del codice stesso (non è questo il caso)

2021-04-14 15:06 UTC, SergioIacobellis commented on app/test/routes/actions/privacy/responses.js
> +}
done

2021-04-14 15:07 UTC, SergioIacobellis commented on app/test/routes/actions/privacy/privacyAcceptanceRoute.test.js
> +  })
se esegui il test va a buon fine, quindi Zoho ti canna. Nessuno ci vieta di applicare una validazione a monte. Ci serve?

2021-04-14 15:10 UTC, SergioIacobellis commented on app/test/routes/actions/privacy/privacyAcceptanceRoute.test.js
> +  it('Privacy Acceptance - Bad request with invalid parameter', async () => {
Il vincolo esiste nell'immagine che segue..Cosa intendi esattamente?
![Capture](https://user-images.githubusercontent.com/80697733/114734179-48398c00-9d44-11eb-8b20-086547dcb9b7.PNG)

2021-04-15 10:08 UTC, andrerinaldi commented on app/test/routes/actions/privacy/privacyAcceptanceRoute.test.js
> +  })
no no, top che lo faccia Zoho.

2021-04-15 10:11 UTC, andrerinaldi commented on app/src/routes/actions/privacy/privacyAcceptanceRoute.js
> +    },
La si può valutare a livello di core, segnamocelo come punto di discussione con Davide e Gabriele in altro momento

2021-04-15 10:29 UTC, SergioIacobellis commented on app/test/routes/actions/privacy/privacyAcceptanceRoute.test.js
> +  it('Privacy Acceptance - Bad request with invalid parameter', async () => {
Inserito nuovo test case - Error 400 - Post without parameters

2021-04-15 10:40 UTC, andrerinaldi approved these changes

2021-04-15 10:40 UTC, merged