Feature/api 2 read privacy policy
responsa/responsa-plugin-amga-reclami pull request #7
Opened 2021-04-16 08:23 UTC by SergioIacobellis

2021-04-16 09:30 UTC, andrerinaldi requested changes
visto che probabilmente tardiamo a fare il merge di tutte le nostre varie pull request.. prenditi un po' di tempo e rinomina bene i file delle due rotte.. le chiamerei banalmente readPrivacyRoute.js e acceptPrivacyRoute.. e come path degli endpoint farei di conseguenza POST /actions/privacy e GET /actions/privacy?email=bla@bla.bla

2021-04-16 09:30 UTC, andrerinaldi commented on app/src/models/getPrivacyAcceptance.js
> +      nullable: true
Perché nullable = true? O c'è o non c'è.. no?

2021-04-16 09:30 UTC, andrerinaldi commented on app/src/routes/actions/privacy/get/getPrivacyAcceptanceRoute.js
> +    }
per la validazione della mail metterei un pattern nello schema.. tipo: 
`pattern: '^\\w+([-+.']\\w+)*@\\w+([-.]\\w+)*\\.\\w+([-.]\\w+)*$'`

Ovviamente indaghiamo sulla bontà della regex.. Comunque validerei il formato della mail sulla nostra interfaccia, indipendentemente da quello che fa Zoho.. e adattiamo i test.
 Poi con il refactoring che faremo i prossimi giorni editiamo anche la POST.

2021-04-16 10:26 UTC, SergioIacobellis commented on app/src/models/getPrivacyAcceptance.js
> +      nullable: true
done

2021-04-16 10:27 UTC, SergioIacobellis commented on app/src/models/getPrivacyAcceptance.js
> +      nullable: true
ho rinominato i file, ma la struttura delle folder è la stessa e per il momento non la cambierei se per te va bene

2021-04-16 10:44 UTC, SergioIacobellis commented on app/src/routes/actions/privacy/get/getPrivacyAcceptanceRoute.js
> +    }
Inserito pattern all'interno dello schema

2021-04-16 10:51 UTC, andrerinaldi requested changes
![image](https://user-images.githubusercontent.com/6502044/115014250-5c9b9700-9eb2-11eb-9c34-58cbfe3e24f6.png)

la folder get tirala via, poi siamo a posto!

2021-04-16 12:07 UTC, davidefinellieuris reviewed
Giusto due cose:
1. manca una gestione degli errori nelle rotte (rispondiamo 400 senza dire perchè)
2. io farei un unico file privacyRoute
3. sistemare i test per le regex 
La prima lo rimandiamo post merge della feature API-7.
La seconda ... ditemi che ne pensate
La terza forse l'aveva già segnalata @andrerinaldi  mi sembra

2021-04-16 13:38 UTC, davidefinellieuris requested changes

2021-04-16 13:38 UTC, davidefinellieuris commented on app/src/routes/actions/privacy/accept/acceptPrivacyRoute.js
> +    reply.code(200)
perchè?

2021-04-16 13:38 UTC, davidefinellieuris commented on app/src/routes/actions/privacy/read/readPrivacyRoute.js
> -      reply.code(400)
come sopra

2021-04-16 13:38 UTC, davidefinellieuris commented on app/test/routes/actions/privacy/read/readPrivacyRoute.test.js
> +    expect(response.statusCode).toEqual(400)
non dovrebbe essere 404?

2021-04-16 13:44 UTC, SergioIacobellis commented on app/src/routes/actions/privacy/read/readPrivacyRoute.js
> -      reply.code(400)
inserita gestione no rows found

2021-04-16 13:53 UTC, davidefinellieuris commented on app/src/routes/actions/privacy/read/readPrivacyRoute.js
> -      reply.code(400)
ok ma ancora non ho capito in acceptPrivacyRoute hai tolto tutta la logica per inserire un reply.code(200)

2021-04-16 13:53 UTC, davidefinellieuris commented on app/src/routes/actions/privacy/accept/acceptPrivacyRoute.js
> +    reply.code(200)
vedi commento sotto

2021-04-16 13:54 UTC, davidefinellieuris commented on app/test/routes/actions/privacy/read/readPrivacyRoute.test.js
> +    expect(response.statusCode).toEqual(400)
nel commit dopo hai messo 200 ... perchè?

2021-04-19 06:33 UTC, SergioIacobellis commented on app/src/routes/actions/privacy/read/readPrivacyRoute.js
> -      reply.code(400)
risolto come concordato venderì

2021-04-19 06:33 UTC, SergioIacobellis commented on app/src/routes/actions/privacy/accept/acceptPrivacyRoute.js
> +    reply.code(200)
risolto come concordato venerdì

2021-04-19 06:34 UTC, SergioIacobellis commented on app/test/routes/actions/privacy/read/readPrivacyRoute.test.js
> +    expect(response.statusCode).toEqual(400)
risolto come concordato venerdì

2021-04-19 08:25 UTC, andrerinaldi approved these changes
ok! mergiamo pure!

2021-04-19 08:55 UTC, merged